

.PHONY : TARGET0
TARGET0 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/add-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/add-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET1
TARGET1 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/addi-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/addi-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET2
TARGET2 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/and-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/and-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET3
TARGET3 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/andi-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/andi-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET4
TARGET4 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/auipc-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/auipc-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET5
TARGET5 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/beq-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/beq-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET6
TARGET6 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/bge-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bge-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET7
TARGET7 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/bgeu-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bgeu-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET8
TARGET8 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/blt-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/blt-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET9
TARGET9 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/bltu-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bltu-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET10
TARGET10 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/bne-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bne-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET11
TARGET11 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/fence-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/fence-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET12
TARGET12 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/jal-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jal-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET13
TARGET13 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/jalr-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jalr-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET14
TARGET14 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/lb-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lb-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET15
TARGET15 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/lbu-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lbu-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET16
TARGET16 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/lh-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lh-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET17
TARGET17 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/lhu-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lhu-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET18
TARGET18 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/lui-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lui-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET19
TARGET19 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/lw-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lw-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET20
TARGET20 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/or-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/or-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET21
TARGET21 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/ori-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/ori-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET22
TARGET22 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sb-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sb-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET23
TARGET23 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sh-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sh-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET24
TARGET24 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sll-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sll-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET25
TARGET25 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/slli-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slli-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET26
TARGET26 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/slt-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slt-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET27
TARGET27 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/slti-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slti-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET28
TARGET28 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sltiu-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltiu-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET29
TARGET29 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sltu-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltu-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET30
TARGET30 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sra-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sra-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET31
TARGET31 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/srai-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srai-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET32
TARGET32 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/srl-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srl-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET33
TARGET33 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/srli-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srli-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET34
TARGET34 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sub-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sub-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET35
TARGET35 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/sw-align-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sw-align-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET36
TARGET36 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/xor-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xor-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike

.PHONY : TARGET37
TARGET37 :
	@cd /home/octonyte/OctoNyte/tests/riscof_work/src/xori-01.S/ref;riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/octonyte/OctoNyte/tests/spike/env/link.ld         -I /home/octonyte/OctoNyte/tests/spike/env/         -I /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/env -mabi=ilp32  /home/octonyte/OctoNyte/tests/external/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xori-01.S -o ref.elf -DTEST_CASE_1=True -DXLEN=32;riscv32-unknown-elf-objdump -D ref.elf > ref.disass;spike